import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * The platform packages (packages/apple, packages/google) are the source of truth for native code, but an app
 * installs @healthspec/expo from npm, where neither package exists and neither is published to CocoaPods or
 * Maven. The Expo module therefore compiles a copy of the sources it needs. Copies are regenerated by
 * `pnpm codegen` and checked by `pnpm codegen:check`, exactly like generated code.
 */
interface VendoredTree {
  /** Source directory (or file), relative to the repository root. */
  from: string;
  /** Destination directory (or file), relative to the repository root. */
  to: string;
  /** Only files with this extension are copied. */
  ext: string;
}

const TREES: VendoredTree[] = [
  { from: 'packages/apple/Sources/HealthSpec/HealthSpecSupport.swift', to: 'libraries/expo-health/ios/Shared/HealthSpecSupport.swift', ext: '.swift' },
  { from: 'packages/google/src/main/kotlin/dev/healthspec', to: 'libraries/expo-health/android/src/main/java/dev/healthspec', ext: '.kt' },
];

/** Directories inside a destination tree that belong to the Expo module itself and are never vendored. */
const OWNED_BY_DESTINATION = ['libraries/expo-health/android/src/main/java/dev/healthspec/expo'];

const banner = (from: string) => `// COPIED from ${from} by \`pnpm codegen\` — edit the original, not this file.\n`;

async function listFiles(dir: string, ext: string): Promise<string[]> {
  const entries = await readdir(dir, { recursive: true, withFileTypes: true }).catch(() => []);
  return entries
    .filter((e) => e.isFile() && e.name.endsWith(ext))
    .map((e) => path.join(e.parentPath, e.name))
    .sort();
}

export interface VendorResult {
  /** destination (repo-relative) → content */
  outputs: Record<string, string>;
  /** destination files that exist but have no source any more */
  orphans: string[];
}

/**
 * @param generated outputs of this codegen run; a vendored file that is itself generated is copied from here
 * rather than from disk, so `--check` compares against what the spec produces, not a possibly stale file.
 */
export async function vendorNativeSources(root: string, generated: Record<string, string>): Promise<VendorResult> {
  const outputs: Record<string, string> = {};
  const orphans: string[] = [];
  for (const tree of TREES) {
    const fromAbs = path.join(root, tree.from);
    const isFile = tree.from.endsWith(tree.ext);
    const sources = isFile ? [fromAbs] : await listFiles(fromAbs, tree.ext);
    const expected = new Set<string>();
    for (const abs of sources) {
      const relFrom = path.relative(root, abs);
      const relTo = isFile ? tree.to : path.join(tree.to, path.relative(fromAbs, abs));
      const content = generated[relFrom] ?? (await readFile(abs, 'utf8'));
      outputs[relTo] = banner(relFrom) + content;
      expected.add(relTo);
    }
    if (isFile) continue;
    for (const abs of await listFiles(path.join(root, tree.to), tree.ext)) {
      const rel = path.relative(root, abs);
      if (OWNED_BY_DESTINATION.some((owned) => rel.startsWith(owned + path.sep))) continue;
      if (!expected.has(rel)) orphans.push(rel);
    }
  }
  return { outputs, orphans };
}
