/**
 * Batch A — full Health Connect coverage (the 16 record types missing after Phase 1) plus their HealthKit
 * counterparts, and the HealthKit-only siblings needed so no concept is lost (basal_energy).
 */
import { dateTime, enumOf, int, num, str, type Entry } from './write.js';

const TEMP_LOCATIONS = ['armpit', 'finger', 'forehead', 'mouth', 'rectum', 'temporal_artery', 'toe', 'ear', 'wrist', 'vagina', 'unknown'];

export const BATCH_A: Entry[] = [
  {
    id: 'menstruation_flow',
    description: 'Menstrual flow observation for a day (or shorter interval).',
    category: 'cycle',
    kind: 'interval',
    aggregate: ['count'],
    hk: {
      kind: 'category',
      identifier: 'HKCategoryTypeIdentifierMenstrualFlow',
      valueField: 'flow',
      values: { unknown: 1, light: 2, medium: 3, heavy: 4, none: 5 },
      metadataFields: { cycleStart: { key: 'HKMenstrualCycleStart', type: 'boolean' } },
    },
    hc: { record: 'MenstruationFlowRecord', permission: 'MENSTRUATION', field: 'flow', notes: ['Health Connect has no "none" flow; it is written as FLOW_UNKNOWN.'] },
    properties: { flow: enumOf(['unknown', 'light', 'medium', 'heavy', 'none']), cycleStart: { type: 'boolean', description: 'First day of a cycle (HealthKit metadata only).' } },
    required: ['flow'],
    examples: [{ flow: 'medium', cycleStart: true }],
  },
  {
    id: 'menstruation_period',
    description: 'A menstrual period as a whole (Health Connect only; HealthKit users derive periods from menstruation_flow with cycleStart).',
    category: 'cycle',
    kind: 'interval',
    aggregate: ['count', 'duration'],
    hc: { record: 'MenstruationPeriodRecord', permission: 'MENSTRUATION' },
    properties: {},
    examples: [{}],
  },
  {
    id: 'ovulation_test',
    description: 'Result of an ovulation (LH / estrogen) test.',
    category: 'cycle',
    kind: 'sample',
    aggregate: ['count'],
    hk: {
      kind: 'category',
      identifier: 'HKCategoryTypeIdentifierOvulationTestResult',
      valueField: 'result',
      values: { negative: 1, positive: 2, inconclusive: 3, high: 4 },
      notes: ['HealthKit: positive = luteinizingHormoneSurge, high = estrogenSurge, inconclusive = indeterminate.'],
    },
    hc: { record: 'OvulationTestRecord', permission: 'OVULATION_TEST', field: 'result' },
    properties: { result: enumOf(['negative', 'positive', 'high', 'inconclusive']) },
    required: ['result'],
    examples: [{ result: 'positive' }],
  },
  {
    id: 'cervical_mucus',
    description: 'Cervical mucus observation.',
    category: 'cycle',
    kind: 'sample',
    aggregate: ['count'],
    hk: {
      kind: 'category',
      identifier: 'HKCategoryTypeIdentifierCervicalMucusQuality',
      valueField: 'appearance',
      values: { dry: 1, sticky: 2, creamy: 3, watery: 4, egg_white: 5 },
      notes: ['HealthKit records appearance only; sensation is Health Connect only.'],
    },
    hc: { record: 'CervicalMucusRecord', permission: 'CERVICAL_MUCUS', fields: { appearance: 'appearance', sensation: 'sensation' } },
    properties: { appearance: enumOf(['dry', 'sticky', 'creamy', 'watery', 'egg_white', 'unusual', 'unknown']), sensation: enumOf(['light', 'medium', 'heavy', 'unknown']) },
    examples: [{ appearance: 'egg_white', sensation: 'medium' }],
  },
  {
    id: 'intermenstrual_bleeding',
    description: 'Spotting / bleeding between periods.',
    category: 'cycle',
    kind: 'sample',
    aggregate: ['count'],
    hk: { kind: 'category', identifier: 'HKCategoryTypeIdentifierIntermenstrualBleeding', values: {} },
    hc: { record: 'IntermenstrualBleedingRecord', permission: 'INTERMENSTRUAL_BLEEDING' },
    properties: {},
    examples: [{}],
  },
  {
    id: 'sexual_activity',
    description: 'Sexual activity event.',
    category: 'cycle',
    kind: 'sample',
    aggregate: ['count'],
    hk: {
      kind: 'category',
      identifier: 'HKCategoryTypeIdentifierSexualActivity',
      values: {},
      metadataFields: { protectionUsed: { key: 'HKSexualActivityProtectionUsed', type: 'boolean', booleanEnum: { true: 'protected', false: 'unprotected' } } },
    },
    hc: { record: 'SexualActivityRecord', permission: 'SEXUAL_ACTIVITY', field: 'protectionUsed' },
    properties: { protectionUsed: enumOf(['protected', 'unprotected', 'unknown']) },
    examples: [{ protectionUsed: 'protected' }],
  },
  {
    id: 'basal_body_temperature',
    description: 'Basal body temperature (measured at rest, typically on waking).',
    category: 'cycle',
    kind: 'sample',
    aggregate: ['avg', 'min', 'max'],
    hk: { kind: 'quantity', identifier: 'HKQuantityTypeIdentifierBasalBodyTemperature', unit: 'degC' },
    hc: { record: 'BasalBodyTemperatureRecord', permission: 'BASAL_BODY_TEMPERATURE', field: 'temperature', unit: 'celsius' },
    omh: 'body-temperature',
    properties: { celsius: num('°C', { minimum: 20, maximum: 50 }), measurementLocation: enumOf(TEMP_LOCATIONS) },
    required: ['celsius'],
    examples: [{ celsius: 36.4 }],
  },
  {
    id: 'basal_metabolic_rate',
    description: 'Basal metabolic rate as an energy *rate* (Health Connect). For HealthKit’s basal energy over an interval see basal_energy.',
    category: 'body',
    kind: 'sample',
    aggregate: ['avg', 'min', 'max'],
    hc: { record: 'BasalMetabolicRateRecord', permission: 'BASAL_METABOLIC_RATE', field: 'basalMetabolicRate', unit: 'kilocaloriesPerDay' },
    properties: { kilocaloriesPerDay: num('kcal/day', { minimum: 0 }) },
    required: ['kilocaloriesPerDay'],
    examples: [{ kilocaloriesPerDay: 1650 }],
  },
  {
    id: 'basal_energy',
    description: 'Resting (basal) energy burned during the interval (HealthKit). Health Connect exposes the rate instead — see basal_metabolic_rate.',
    category: 'activity',
    kind: 'interval',
    aggregate: ['sum'],
    hk: { kind: 'quantity', identifier: 'HKQuantityTypeIdentifierBasalEnergyBurned', unit: 'kcal' },
    properties: { kilocalories: num('kcal', { minimum: 0 }) },
    required: ['kilocalories'],
    examples: [{ kilocalories: 68.2 }],
  },
  {
    id: 'body_water_mass',
    description: 'Total body water mass.',
    category: 'body',
    kind: 'sample',
    aggregate: ['avg', 'min', 'max'],
    hc: { record: 'BodyWaterMassRecord', permission: 'BODY_WATER_MASS', field: 'mass', unit: 'kilograms' },
    properties: { kilograms: num('kg', { exclusiveMinimum: 0, maximum: 500 }) },
    required: ['kilograms'],
    examples: [{ kilograms: 41.2 }],
  },
  {
    id: 'bone_mass',
    description: 'Bone mass.',
    category: 'body',
    kind: 'sample',
    aggregate: ['avg', 'min', 'max'],
    hc: { record: 'BoneMassRecord', permission: 'BONE_MASS', field: 'mass', unit: 'kilograms' },
    properties: { kilograms: num('kg', { exclusiveMinimum: 0, maximum: 100 }) },
    required: ['kilograms'],
    examples: [{ kilograms: 3.1 }],
  },
  {
    id: 'cycling_cadence',
    description: 'Pedalling cadence sample.',
    category: 'activity',
    kind: 'sample',
    aggregate: ['avg', 'min', 'max'],
    hk: { kind: 'quantity', identifier: 'HKQuantityTypeIdentifierCyclingCadence', unit: 'count/min', since: 'iOS 17' },
    hc: { record: 'CyclingPedalingCadenceRecord', permission: 'CYCLING_PEDALING_CADENCE', field: 'samples[].revolutionsPerMinute', unit: 'rpm', series: true },
    properties: { rpm: num('rpm', { minimum: 0, maximum: 400 }) },
    required: ['rpm'],
    examples: [{ rpm: 88 }],
  },
  {
    id: 'steps_cadence',
    description: 'Step cadence sample (Health Connect only).',
    category: 'activity',
    kind: 'sample',
    aggregate: ['avg', 'min', 'max'],
    hc: { record: 'StepsCadenceRecord', permission: 'STEPS_CADENCE', field: 'samples[].rate', unit: 'steps/min', series: true },
    properties: { stepsPerMinute: num('steps/min', { minimum: 0, maximum: 400 }) },
    required: ['stepsPerMinute'],
    examples: [{ stepsPerMinute: 112 }],
  },
  {
    id: 'elevation_gained',
    description: 'Elevation gained during the interval (Health Connect only; HealthKit keeps it as workout metadata).',
    category: 'activity',
    kind: 'interval',
    aggregate: ['sum'],
    hc: { record: 'ElevationGainedRecord', permission: 'ELEVATION_GAINED', field: 'elevation', unit: 'meters' },
    properties: { meters: num('m') },
    required: ['meters'],
    examples: [{ meters: 140.5 }],
  },
  {
    id: 'power',
    description: 'Power output sample, activity-agnostic (Health Connect). HealthKit splits power by activity — see cycling_power and running_power.',
    category: 'activity',
    kind: 'sample',
    aggregate: ['avg', 'min', 'max'],
    hc: { record: 'PowerRecord', permission: 'POWER', field: 'samples[].power', unit: 'watts', series: true },
    properties: { watts: num('W', { minimum: 0 }) },
    required: ['watts'],
    examples: [{ watts: 212 }],
  },
  {
    id: 'speed',
    description: 'Speed sample, activity-agnostic (Health Connect). HealthKit splits speed by activity — see walking_speed, running_speed, cycling_speed.',
    category: 'activity',
    kind: 'sample',
    aggregate: ['avg', 'min', 'max'],
    hc: { record: 'SpeedRecord', permission: 'SPEED', field: 'samples[].speed', unit: 'metersPerSecond', series: true },
    properties: { metersPerSecond: num('m/s', { minimum: 0 }) },
    required: ['metersPerSecond'],
    examples: [{ metersPerSecond: 3.2 }],
  },
  {
    id: 'exercise_route',
    description: 'GPS route of an exercise session. Read with readRoute(sessionId): Health Connect asks the user per session; HealthKit reads the route series linked to the workout.',
    category: 'activity',
    kind: 'interval',
    aggregate: ['count'],
    hk: { kind: 'series', identifier: 'HKWorkoutRouteTypeIdentifier', notes: ['HKSeriesType.workoutRoute(); points arrive as CLLocation batches.'] },
    hc: { record: 'ExerciseRoute', permission: 'EXERCISE_ROUTE', special: true, read: false, write: true, notes: ['Read consent is per session via requestExerciseRoute (no READ permission exists); WRITE_EXERCISE_ROUTE covers writes.'] },
    properties: {
      sessionId: str({ description: 'Id of the exercise_session this route belongs to.' }),
      points: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            time: dateTime(),
            latitude: num('°', { minimum: -90, maximum: 90 }),
            longitude: num('°', { minimum: -180, maximum: 180 }),
            altitudeMeters: num('m'),
            horizontalAccuracyMeters: num('m', { minimum: 0 }),
            verticalAccuracyMeters: num('m', { minimum: 0 }),
          },
          required: ['time', 'latitude', 'longitude'],
          additionalProperties: false,
        },
      },
    },
    required: ['points'],
    examples: [{ sessionId: 'abc', points: [{ time: '2026-08-21T07:00:00Z', latitude: 37.5665, longitude: 126.978, altitudeMeters: 38 }] }],
  },
];

void int;
