import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Just enough reading of Info.plist, entitlements, AndroidManifest.xml and gradle.properties for the doctor. These
 * files are generated by Expo prebuild in a regular shape, so a dependency-free reader is sufficient and keeps
 * the CLI installable anywhere.
 */

export type PlistValue = string | boolean | number | PlistValue[] | { [key: string]: PlistValue };

const decode = (s: string) => s.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, '&');

/** An XML property list as plain values. Enough of the format for the files Expo prebuild writes. */
export function readPlist(file: string): Record<string, PlistValue> {
  const xml = readFileSync(file, 'utf8');
  const tokens = [...xml.matchAll(/<(\/?)(dict|array|key|string|integer|real|true|false|date|data)(\/?)>([^<]*)/g)];
  let i = tokens.findIndex((t) => t[2] === 'dict' || t[2] === 'array');
  if (i < 0) return {};

  function value(): PlistValue {
    const t = tokens[i++];
    if (!t) throw new Error(`${file}: unexpected end of property list`);
    const [, closing, tag, selfClosing, text = ''] = t;
    if (closing) throw new Error(`${file}: unexpected </${tag}>`);
    switch (tag) {
      case 'dict': {
        const out: Record<string, PlistValue> = {};
        if (selfClosing) return out;
        while (tokens[i] && !(tokens[i]![1] && tokens[i]![2] === 'dict')) {
          const key = tokens[i++];
          if (key?.[2] !== 'key') throw new Error(`${file}: expected <key> in <dict>`);
          const name = decode(key[4] ?? '');
          i++; // </key>
          out[name] = value();
        }
        i++; // </dict>
        return out;
      }
      case 'array': {
        const out: PlistValue[] = [];
        if (selfClosing) return out;
        while (tokens[i] && !(tokens[i]![1] && tokens[i]![2] === 'array')) out.push(value());
        i++; // </array>
        return out;
      }
      case 'true':
        return true;
      case 'false':
        return false;
      case 'integer':
      case 'real':
        i++;
        return Number(text);
      default:
        if (selfClosing) return '';
        i++; // closing tag
        return decode(text);
    }
  }

  const root = value();
  return typeof root === 'object' && !Array.isArray(root) ? root : {};
}

export interface ManifestElement {
  name: string;
  attributes: Record<string, string>;
  /** raw inner XML */
  inner: string;
}

const attributesOf = (tag: string): Record<string, string> =>
  Object.fromEntries([...tag.matchAll(/([\w:.-]+)="([^"]*)"/g)].map((m) => [m[1] ?? '', decode(m[2] ?? '')]));

/** Every `<tag …/>` or `<tag …>…</tag>` element with the given name, anywhere in the document. */
export function elements(xml: string, tag: string): ManifestElement[] {
  const out: ManifestElement[] = [];
  const re = new RegExp(`<${tag}\\b([^>]*?)(/>|>([\\s\\S]*?)</${tag}>)`, 'g');
  for (const m of xml.matchAll(re)) out.push({ name: tag, attributes: attributesOf(m[1] ?? ''), inner: m[3] ?? '' });
  return out;
}

export function readProperties(file: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('!')) continue;
    const i = trimmed.search(/[=:]/);
    if (i > 0) out[trimmed.slice(0, i).trim()] = trimmed.slice(i + 1).trim();
  }
  return out;
}

/** Files with the given suffix one directory below `dir` (Expo's ios/<AppName>/ layout). */
export function filesOneLevelDown(dir: string, suffix: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith('.') && d.name !== 'Pods' && !d.name.endsWith('.xcodeproj') && !d.name.endsWith('.xcworkspace'))
    .flatMap((d) => readdirSync(path.join(dir, d.name)).filter((f) => f.endsWith(suffix)).map((f) => path.join(dir, d.name, f)));
}
